import type { LyricLine } from '~/types'

// Local lyrics data - will be replaced by API calls later
const localLyricsData: Record<number, LyricLine[]> = {
  1: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 15, text: 'De nos jours plus rien de va,', type: 'COUPLET', number: 1 },
    { time: 17, text: 'Que ce soit ici ou là-bas,', type: 'COUPLET', number: 1 },
    { time: 20, text: 'Ils sont ici pour nous faire chier', type: 'COUPLET', number: 1 },
    { time: 23, text: 'Je parle bien sur des étrangers !', type: 'COUPLET', number: 1 },
    { time: 26, text: 'Il y en a de toute sorte,', type: 'COUPLET', number: 1 },
    { time: 28, text: "C'est comme des cartes pokémon,", type: 'COUPLET', number: 1 },
    { time: 31, text: 'Mais malheureusement sur leur carte', type: 'COUPLET', number: 1 },
    { time: 33, text: 'Que des statistiques qui déconnent !', type: 'COUPLET', number: 1 },
    { time: 36, text: 'On ne veut aussi pas les collectionner !', type: 'COUPLET', number: 1 },
    { time: 39, text: "Car un pokédex c'est fait pour être parfait", type: 'COUPLET', number: 1 },
    { time: 42, text: "La dernière fois que j'en ai vu", type: 'COUPLET', number: 1 },
    { time: 44, text: "C'était pour leur cracher dessus.", type: 'COUPLET', number: 1 },
    { time: 49, text: "Les Arabes c'est dehors !", type: 'REFRAIN', number: 1 },
    { time: 52, text: "On n'en veut plus dans le décor !", type: 'REFRAIN', number: 1 },
    { time: 55, text: "Les maghrébins c'est dehors !", type: 'REFRAIN', number: 1 },
    { time: 57, text: "Impossible qu'ils ne s'améliorent !", type: 'REFRAIN', number: 1 },
    { time: 60, text: "Les bridés c'est dehors !", type: 'REFRAIN', number: 1 },
    { time: 63, text: 'Ce ne sont pas des trésor !', type: 'REFRAIN', number: 1 },
    { time: 65, text: "Les négros c'est dehors !", type: 'REFRAIN', number: 1 },
    { time: 68, text: 'Ah non pas eux,', type: 'REFRAIN', number: 1 },
    { time: 69, text: 'On en veut pour nos champs !', type: 'REFRAIN', number: 1 },
    { time: 72, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 76, text: "Avec la monté de l'extrême droite", type: 'COUPLET', number: 2 },
    { time: 79, text: "Oh mon dieu qu'elle aubaine", type: 'COUPLET', number: 2 },
    { time: 81, text: 'Depuis maintenant quelques années à droites', type: 'COUPLET', number: 2 },
    { time: 84, text: 'On voit cette magnifique Madame Le Pen', type: 'COUPLET', number: 2 },
    { time: 87, text: 'Ça lui a valu la prison', type: 'COUPLET', number: 2 },
    { time: 90, text: 'Justice imparfaite', type: 'COUPLET', number: 2 },
    { time: 92, text: 'Heureusement, il est bientôt là,', type: 'COUPLET', number: 2 },
    { time: 95, text: 'On le verra en 2027', type: 'COUPLET', number: 2 },
    { time: 97, text: 'Je parle bien sûr de ce magnifique Bardella !', type: 'COUPLET', number: 2 },
    { time: 100, text: "Certains pensent qu'il n'a aucune chance", type: 'COUPLET', number: 2 },
    { time: 103, text: 'Moi je pense qu\'il peut se hisser', type: 'COUPLET', number: 2 },
    { time: 105, text: "Avec sa beauté d'esprit et son intelligence", type: 'COUPLET', number: 2 },
    { time: 108, text: 'Sur le siège le plus haut et le plus prisé de France', type: 'COUPLET', number: 2 },
    { time: 114, text: "Les Arabes c'est dehors !", type: 'REFRAIN', number: 2 },
    { time: 117, text: "On n'en veut plus dans le décor !", type: 'REFRAIN', number: 2 },
    { time: 120, text: "Les maghrébins c'est dehors !", type: 'REFRAIN', number: 2 },
    { time: 123, text: "Impossible qu'ils ne s'améliorent !", type: 'REFRAIN', number: 2 },
    { time: 126, text: "Les bridés c'est dehors !", type: 'REFRAIN', number: 2 },
    { time: 128, text: 'Ce ne sont pas des trésor !', type: 'REFRAIN', number: 2 },
    { time: 130, text: "Les négros c'est dehors !", type: 'REFRAIN', number: 2 },
    { time: 133, text: 'Ah non pas eux,', type: 'REFRAIN', number: 2 },
    { time: 135, text: 'On en veut pour nos champs !', type: 'REFRAIN', number: 2 },
    { time: 137, text: '...', type: 'INSTRUMENTAL', number: 2 },
    { time: 138, text: 'On les sent à 10 000', type: 'BRIDGE', number: 1 },
    { time: 139, text: 'Et ça remplit nos narines', type: 'BRIDGE', number: 1 },
    { time: 140, text: "Ce n'est pas de la vanille", type: 'BRIDGE', number: 1 },
    { time: 142, text: 'Mais je dirais des latrines', type: 'BRIDGE', number: 1 },
    { time: 143, text: 'Avec un mélange de poubelles', type: 'BRIDGE', number: 1 },
    { time: 145, text: "Qu'on utilise pour le compost", type: 'BRIDGE', number: 1 },
    { time: 148, text: "Bien pourris au fond d'une ruelle", type: 'BRIDGE', number: 1 },
    { time: 151, text: "Où n'y va même pas la poste", type: 'BRIDGE', number: 1 },
    { time: 153, text: 'Ça sent même la marée basse', type: 'BRIDGE', number: 1 },
    { time: 156, text: "Pas étonnant vu qu'ils y meurent", type: 'BRIDGE', number: 1 },
    { time: 159, text: 'On leur dit buvez pas la tasse', type: 'BRIDGE', number: 1 },
    { time: 161, text: 'Mais ils sont plus cons que des chômeurs', type: 'BRIDGE', number: 1 },
    { time: 169, text: "Les Arabes c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 172, text: 'Hey ! Hey ! Hey ! Hey !', type: 'REFRAIN', number: 3 },
    { time: 175, text: "Les Magrébins c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 177, text: 'Hey ! Hey ! Hey ! Hey !', type: 'REFRAIN', number: 3 },
    { time: 185, text: "Les Arabes c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 188, text: "On n'en veut plus dans le décor !", type: 'REFRAIN', number: 3 },
    { time: 191, text: "Les maghrébins c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 193, text: "Impossible qu'ils ne s'améliorent !", type: 'REFRAIN', number: 3 },
    { time: 196, text: "Les bridés c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 199, text: 'Ce ne sont pas des trésor !', type: 'REFRAIN', number: 3 },
    { time: 202, text: "Les négros c'est dehors !", type: 'REFRAIN', number: 3 },
    { time: 204, text: 'Ah non pas eux,', type: 'REFRAIN', number: 3 },
    { time: 206, text: 'On en veut pour nos champs !', type: 'REFRAIN', number: 3 },
  ],
  2: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 10, text: 'Cette soldate dont nous avons parlé', type: 'COUPLET', number: 1 },
    { time: 13, text: 'Ses grands exploits, nous les avons comptés', type: 'COUPLET', number: 1 },
    { time: 18, text: 'Mais à présent, il nous faut esquisser', type: 'COUPLET', number: 1 },
    { time: 23, text: 'Son corps mythique à la noble beauté', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Ni des chansons, ni des contes, ni des fables', type: 'COUPLET', number: 1 },
    { time: 32, text: 'Nous n\'avions vu femme aussi redoutable', type: 'COUPLET', number: 1 },
    { time: 35, text: 'D\'aucun pays, de France et de Navarre', type: 'COUPLET', number: 1 },
    { time: 37, text: 'Une soldate n\'égala son fier charme', type: 'COUPLET', number: 1 },
    { time: 40, text: 'Ses doux cheveux semblant à des fils d\'or', type: 'COUPLET', number: 1 },
    { time: 42, text: 'Une fois lâchés, lui caressent les épaules', type: 'COUPLET', number: 1 },
    { time: 45, text: 'De tous les êtres que la nature façonne', type: 'COUPLET', number: 1 },
    { time: 48, text: 'Je vous assure qu\'elle en est la plus bonne', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Son beau visage, au teint clair, lumineux', type: 'COUPLET', number: 1 },
    { time: 53, text: 'Ne rivalise qu\'avec ses doux yeux bleus', type: 'COUPLET', number: 1 },
    { time: 55, text: 'Ce bleu marin, chatoyants tel un feu', type: 'COUPLET', number: 1 },
    { time: 58, text: 'Révèle sa rage, un courage merveileux', type: 'COUPLET', number: 1 },
    { time: 60, text: 'Son nez parfait, élégant, délicat', type: 'COUPLET', number: 1 },
    { time: 63, text: 'Est un trésor que mère nature créa', type: 'COUPLET', number: 1 },
    { time: 65, text: 'Et ses lèvres charnues sont un régal', type: 'COUPLET', number: 1 },
    { time: 68, text: 'Pour qui aime pratiquer le sexe oral', type: 'COUPLET', number: 1 },
    { time: 71, text: 'Gabrielle, ton corps s\'embrase de beauté', type: 'REFRAIN', number: 1 },
    { time: 74, text: 'Gabrielle, les hommes se prosternent à tes quiquets', type: 'REFRAIN', number: 1 },
    { time: 76, text: 'Car tu détiens le pouvoir de les dominer', type: 'REFRAIN', number: 1 },
    { time: 79, text: 'Gabrielle, les bites tu fais lever', type: 'REFRAIN', number: 1 },
    { time: 81, text: 'Gabrielle, si le désir n\'existait pas', type: 'REFRAIN', number: 1 },
    { time: 84, text: 'Gabrielle, grâce à ton corps tu le créas', type: 'REFRAIN', number: 1 },
    { time: 86, text: 'Car la gaule est conquise, rien qu\'à te voir', type: 'REFRAIN', number: 1 },
    { time: 89, text: 'Gabrielle, les bites s\'élèvent haut devant toi', type: 'REFRAIN', number: 1 },
    { time: 92, text: 'Il me faut m\'attarder à présent sur sa gorge', type: 'REFRAIN', number: 1 },
    { time: 97, text: 'Que dis-je, ce gouffre, cette montagne des Vosges', type: 'REFRAIN', number: 1 },
    { time: 99, text: 'Si dure à monter, si bonne à sauter', type: 'REFRAIN', number: 1 },
    { time: 102, text: 'Gabrielle est la reine des décolletés', type: 'REFRAIN', number: 1 },
    { time: 104, text: 'J\'aimerais la toucher, la sentir dans mes mains', type: 'COUPLET', number: 2 },
    { time: 107, text: 'Cette chair opulente qui lui forme ses seins', type: 'COUPLET', number: 2 },
    { time: 109, text: 'Ils sont assurément de la main d\'un divin', type: 'COUPLET', number: 2 },
    { time: 112, text: 'Ou du moins, ont-il été sculptés par Odin', type: 'COUPLET', number: 2 },
    { time: 114, text: 'Je vous prie de me laisser admirer', type: 'COUPLET', number: 2 },
    { time: 116, text: 'Seigneur, son ventre et sa taille si musclée', type: 'COUPLET', number: 2 },
    { time: 119, text: 'Ses abdos forts, sa chute de reins courbée', type: 'COUPLET', number: 2 },
    { time: 121, text: 'Qui nous mènent droit vers l\'entre désirée', type: 'COUPLET', number: 2 },
    { time: 124, text: 'Je ne pourrais vous décrire à quel point', type: 'COUPLET', number: 2 },
    { time: 127, text: 'Elle a un si beau, si joli vagin', type: 'COUPLET', number: 2 },
    { time: 129, text: 'Les mots me manquent pour ce portail pubien', type: 'COUPLET', number: 2 },
    { time: 132, text: 'Qui a vu tant de monde qui semble sans fin', type: 'COUPLET', number: 2 },
    { time: 135, text: 'Gabrielle, ton corps s\'embrase de beauté', type: 'REFRAIN', number: 2 },
    { time: 137, text: 'Gabrielle, les hommes se prosternent à tes pieds', type: 'REFRAIN', number: 2 },
    { time: 140, text: 'Car tu détiens le pouvoir de les dominer', type: 'REFRAIN', number: 2 },
    { time: 142, text: 'Gabrielle, les bites tu fais lever', type: 'REFRAIN', number: 2 },
    { time: 145, text: 'Gabrielle, si le désir n\'existait pas', type: 'REFRAIN', number: 2 },
    { time: 147, text: 'Gabrielle, grâce à ton corps tu le créas', type: 'REFRAIN', number: 2 },
    { time: 149, text: 'Car la Gaule est conquise rien qu\'à te voir', type: 'REFRAIN', number: 2 },
    { time: 153, text: 'Gabrielle, les bites s\'élèvent haut devant toi', type: 'REFRAIN', number: 2 },
    { time: 156, text: 'Gabrielle, ton corps est ardent', type: 'REFRAIN', number: 2 },
    { time: 161, text: 'Comme le feu des enfers', type: 'REFRAIN', number: 2 },
    { time: 168, text: 'Gabrielle, ton corps est celui', type: 'REFRAIN', number: 2 },
    { time: 171, text: 'D\'une femme militaire', type: 'REFRAIN', number: 2 },
    { time: 178, text: 'Gabrielle, ton corps s\'embrase de beauté', type: 'REFRAIN', number: 2 },
    { time: 181, text: 'Gabrielle, les hommes se prosternent à tes pieds', type: 'REFRAIN', number: 2 },
    { time: 184, text: 'Car tu détiens le pouvoir de les dominer', type: 'REFRAIN', number: 2 },
    { time: 186, text: 'Gabrielle, les bites tu fais lever', type: 'REFRAIN', number: 2 },
    { time: 189, text: 'Gabrielle, si le désir n\'existait pas', type: 'REFRAIN', number: 2 },
    { time: 191, text: 'Gabrielle, grâce à ton corps tu le créas', type: 'REFRAIN', number: 2 },
    { time: 194, text: 'Car la Gaule est conquise rien qu\'à te voir', type: 'REFRAIN', number: 2 },
    { time: 196, text: 'Gabrielle, les bites s\'élèvent haut devant toi', type: 'REFRAIN', number: 2 }, 
    { time: 200, text: '...', type: 'INSTRUMENTAL', number: 2 }
    
  ],
  3: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 3 },
    { time: 14, text: 'Aujourd\'hui, attaquons-nous à une majorité de minorités', type: 'COUPLET', number: 1 },
    { time: 21, text: 'Je pense que vous savez déjà de qui nous allons parler', type: 'COUPLET', number: 1 },
    { time: 27, text: 'Je parle bien sûr de tous ces petits fils de putes', type: 'COUPLET', number: 1 },
    { time: 34, text: 'Vivement qu\'on leur mette des culbutes', type: 'COUPLET', number: 1 },
    { time: 38, text: 'Ils sont là à gueuler dans les manifs, enfin on devrait plutôt dire "iels"', type: 'COUPLET', number: 1 },
    { time: 43.5, text: 'Ça a des combats insignifiants, débiles, idiots et superficiels', type: 'COUPLET', number: 1 },
    { time: 47, text: 'Trop occupés à oublier de se raser que de réviser leur cours de SVT', type: 'COUPLET', number: 1 },
    { time: 51, text: 'S\'il vous plaît, retournez à l\'école et quittez votre minorité', type: 'COUPLET', number: 1 },
    { time: 56, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 1 },
    { time: 60, text: 'T\'es une fille quand t\'as une zaza, t\'es un garçon quand t\'as un zouzou', type: 'REFRAIN', number: 1 },
    { time: 64, text: 'Arrêtez de nous faire chier avec tous vos genres qui sortent de la binarité', type: 'REFRAIN', number: 1 },
    { time: 67, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 1 },
    { time: 70, text: 'Évidemment, nous savons que vous n\'avez rien sous le caillou', type: 'REFRAIN', number: 1 },
    { time: 74, text: 'Mais s\'il vous plaît, ayez un minimum de civilité', type: 'REFRAIN', number: 1 },
    { time: 79, text: 'Woke, mais qu\'est-ce que ça veut dire ?', type: 'COUPLET', number: 2 },
    { time: 83, text: 'Ça fait maintenant 30 ans que ce mot existe', type: 'COUPLET', number: 2 },
    { time: 85, text: 'Est-ce un mot dans la langue de Shakespeare ?', type: 'COUPLET', number: 2 },
    { time: 87, text: 'Ces connards se prennent pour des linguistes', type: 'COUPLET', number: 2 },
    { time: 89, text: 'D\'après eux, c\'est être conscient des problèmes sociétaux', type: 'COUPLET', number: 2 },
    { time: 92, text: 'Liés à la justice sociale et à l\'égalité raciale', type: 'COUPLET', number: 2 },
    { time: 95, text: 'Mais déjà ça, on discerne quelque chose de pas trop réglo', type: 'COUPLET', number: 2 },
    { time: 99, text: 'Pour eux, ils séparent les noirs, les arabes et les gens normaux', type: 'COUPLET', number: 2 },
    { time: 102, text: 'Alors excusez-moi, bande de gros gauchos, bande d\'enculés', type: 'COUPLET', number: 2 },
    { time: 106, text: 'Pendant que vous vous battez pour rassembler les gens différents', type: 'COUPLET', number: 2 },
    { time: 109, text: 'Nous les fachos, on se bat pour mettre en lumière cette multiculturalité', type: 'COUPLET', number: 2 },
    { time: 113, text: 'Alors que vous vous cachez souillés, brutalisez la culture des gens', type: 'COUPLET', number: 2 },
    { time: 118, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 2 },
    { time: 122, text: 'T\'es une fille quand t\'as une zaza, t\'es un garçon quand t\'as un zouzou', type: 'REFRAIN', number: 2 },
    { time: 126, text: 'Arrêtez de nous faire chier avec tous vos genres qui sortent de la binarité', type: 'REFRAIN', number: 2 },
    { time: 130, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 2 },
    { time: 133, text: 'Évidemment, nous savons que vous n\'avez rien sous le caillou', type: 'REFRAIN', number: 2 },
    { time: 137, text: 'Mais s\'il vous plaît, ayez un minimum de civilité', type: 'REFRAIN', number: 2 },
    { time: 141, text: 'Après les woke, parlons de hommes déconstruits', type: 'COUPLET', number: 3 },
    { time: 146, text: 'Mais la seule chose qui est déconstruite chez moi, c\'est ta mère', type: 'COUPLET', number: 3 },
    { time: 150, text: 'Car l\'idée d\'aller à la cuisine, la penderie et la laverie', type: 'COUPLET', number: 3 },
    { time: 154, text: 'Ça me donne assurément un énorme mal de mer', type: 'COUPLET', number: 3 },
    { time: 158, text: 'Vous n\'arrêtez pas de nous faire chier avec la galanterie', type: 'COUPLET', number: 3 },
    { time: 161, text: 'On paie le resto, ne vous étonnez pas de perdre 20% de votre salaire', type: 'COUPLET', number: 3 },
    { time: 165, text: 'Si vous voulez qu\'on soit déconstruits, soyez-le vous-même aussi', type: 'COUPLET', number: 3 },
    { time: 168.5, text: 'Y\'en aura le bol de perdre l\'argent, tout ça pour aucune récompense derrière', type: 'COUPLET', number: 3 },
    { time: 172, text: 'Nous, ce qu\'on veut, c\'est se faire plaisir', type: 'COUPLET', number: 3 },
    { time: 174, text: 'Mais attention, y\'a des limites', type: 'COUPLET', number: 3 },
    { time: 176, text: 'Les poils, c\'est non ! Le chômage, c\'est non ! Les antifrançais, non ! Arrière !', type: 'COUPLET', number: 3 },
    { time: 179.5, text: 'Mais attention j\'commence à divaguer, j\'vais parler frontières et ce que ça délimite', type: 'COUPLET', number: 3 },
    { time: 183, text: 'Passons rapidement à la suite avant que ça se barre en couille à ma manière', type: 'COUPLET', number: 3 },
    { time: 189, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 3 },
    { time: 192, text: 'T\'es une fille quand t\'as une zaza, t\'es un garçon quand t\'as un zouzou', type: 'REFRAIN', number: 3 },
    { time: 196, text: 'Arrêtez de nous faire chier avec tous vos genres qui sortent de la binarité', type: 'REFRAIN', number: 3 },
    { time: 199, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 3 },
    { time: 202, text: 'Évidemment, nous savons que vous n\'avez rien sous le caillou', type: 'REFRAIN', number: 3 },
    { time: 206, text: 'Mais s\'il vous plaît, ayez un minimum de civilité', type: 'REFRAIN', number: 3 },
    { time: 213, text: 'Les woke et la déconstruction, qu\'ai-je bien pus oublier ?', type: 'COUPLET', number: 4 },
    { time: 217, text: 'Oh mon Dieu, mais bien sûr, parlons des gros et de leur body-positivité', type: 'COUPLET', number: 4 },
    { time: 220, text: 'Je suis désolé, mais quand tu pèses 250 kilos, t\'as du diabète', type: 'COUPLET', number: 4 },
    { time: 225, text: 'Et que t\'as du mal à te lever', type: 'COUPLET', number: 4 },
    { time: 227, text: 'C\'est que bien évidemment, t\'es en extrême mauvaise santé', type: 'COUPLET', number: 4 },
    { time: 231, text: '"Oui, nous on peut pas prendre l\'avion car les places sont trop petites"', type: 'COUPLET', number: 4 },
    { time: 239, text: 'Fais pas chier, prends deux places', type: 'COUPLET', number: 4 },
    { time: 241, text: 'Ce n\'est pas nous qui sommes responsables, de la moitié de la consommation de kérosène', type: 'COUPLET', number: 4 },
    { time: 245, text: 'On a encore de la chance qu\'au décollage l\'avion ne fait pas du surplace', type: 'COUPLET', number: 4 },
    { time: 249, text: 'Pourquoi, à ton avis, il n\'y a pas d\'obèses dans les statues gréco-romaines ?', type: 'COUPLET', number: 4 },
    { time: 252, text: 'Encore une fois, tous ces gens s\'inventent un combat qui n\'existe pas', type: 'COUPLET', number: 4 },
    { time: 256, text: 'J\'en ai de plus en plus ras le bol de ces mangeurs de merde', type: 'COUPLET', number: 4 },
    { time: 259, text: 'À chaque discussion et chaque débat je leur dis "Putain, mais je t\'emmerde"', type: 'COUPLET', number: 4 },
    { time: 263, text: 'Car ils sont bloqués dans un idéal', type: 'COUPLET', number: 4 },
    { time: 264, text: 'Alors qu\'en France, c\'est magnifique, il n\'y a aucun débat', type: 'COUPLET', number: 4 },
    { time: 270, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 4 },
    { time: 272, text: 'T\'es une fille quand t\'as une zaza, t\'es un garçon quand t\'as un zouzou', type: 'REFRAIN', number: 4 },
    { time: 276, text: 'Arrêtez de nous faire chier avec tous vos genres qui sortent de la binarité', type: 'REFRAIN', number: 4 },
    { time: 280, text: 'Les LGBTQIA+, ces grands fous', type: 'REFRAIN', number: 4 },
    { time: 282, text: 'Évidemment, nous savons que vous n\'avez rien sous le caillou', type: 'REFRAIN', number: 4 },
    { time: 287, text: 'Mais s\'il vous plaît, ayez un minimum de civilité', type: 'REFRAIN', number: 4 },
    { time: 296, text: 'Hey, hey, hey', type: 'REFRAIN', number: 4 },
    { time: 304, text: 'Hey, hey', type: 'REFRAIN', number: 4 },
  ],

  4: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 40, text: 'Moi la soldate au service de la france', type: 'COUPLET', number: 1 },
    { time: 45, text: 'Je me battrai, sans relâche, déférente.', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Pour libérer de la vague immigrante', type: 'COUPLET', number: 1 },
    { time: 55, text: 'Notre nation, suffocante, implorante.', type: 'COUPLET', number: 1 },
    { time: 60, text: 'Quand je me lève, je me sens submergée', type: 'COUPLET', number: 1 },
    { time: 62, text: 'Par ces arabes et ces noirs étrangers', type: 'COUPLET', number: 1 },
    { time: 64, text: 'Je ne peux m\'arrêter de m\'inquiéter', type: 'COUPLET', number: 1 },
    { time: 68, text: 'Pour l\'avenir de notre souveraineté', type: 'COUPLET', number: 1 },
    { time: 70, text: 'J\'en ai assez, qu\'on perde notre histoire', type: 'COUPLET', number: 1 },
    { time: 72.5, text: 'Notre héritage, nos chants, notre mémoire', type: 'COUPLET', number: 1 },
    { time: 75, text: 'Notre culture est tenue en otage', type: 'COUPLET', number: 1 },
    { time: 77.5, text: 'Par l\'immigré, cet être haïssable', type: 'COUPLET', number: 1 },
    { time: 83, text: 'Alors je lève le poing, haut, franc et fort', type: 'REFRAIN', number: 1 },
    { time: 87, text: 'Pour montrer ma colère et protéger mon corps', type: 'REFRAIN', number: 1 },
    { time: 89, text: 'Je veux garder espoir de déjouer la mort', type: 'REFRAIN', number: 1 },
    { time: 92, text: 'Je ne veux pas qu\'on m\'oublie et qu\'on me déshonore', type: 'REFRAIN', number: 1 },
    { time: 94, text: 'Pour la patrie, j\'ai sacrifié ma vie', type: 'REFRAIN', number: 1 },
    { time: 97, text: 'Pour la nation, je renonce à mon nom', type: 'REFRAIN', number: 1 },
    { time: 99, text: 'Pour les Français, j\'irai jusqu\'au bûcher', type: 'REFRAIN', number: 1 },
    { time: 102, text: 'Et pour ma religion, j\'irai au front', type: 'REFRAIN', number: 1 },
    { time: 105, text: '...', type: 'INSTRUMENTAL', number: 2 },
    { time: 114, text: 'Sur nos visages, le vent sèche nos larmes', type: 'COUPLET', number: 2 },
    { time: 120, text: 'Elles ont coulé à l\'appel de nos armes', type: 'COUPLET', number: 2 },
    { time: 124, text: 'Nous vengerons la mort des camarades', type: 'COUPLET', number: 2 },
    { time: 129, text: 'Nos frères d\'armes dont éteinte est la flamme', type: 'COUPLET', number: 2 },
    { time: 134.5, text: 'Car des victimes, il y en a eu mille', type: 'COUPLET', number: 2 },
    { time: 137, text: 'Abattues par cette vague clandestine', type: 'COUPLET', number: 2 },
    { time: 139, text: 'Faites par ces criminels, ces incivils', type: 'COUPLET', number: 2 },
    { time: 142, text: 'Ces délinquants assassinent notre patrie', type: 'COUPLET', number: 2 },
    { time: 145, text: 'Je prends épée, pactage et plastron', type: 'COUPLET', number: 2 },
    { time: 147, text: 'Je me prépare pour garder mon bastion', type: 'COUPLET', number: 2 },
    { time: 149, text: 'Je suis prête pour défendre ma maison', type: 'COUPLET', number: 2 },
    { time: 152, text: 'Je n\'ai qu\'une mission', type: 'COUPLET', number: 2 },
    { time: 153, text: 'Stopper l\'immigration', type: 'COUPLET', number: 2 },
    { time: 155, text: 'Alors je lève le poing haut, franc et fort', type: 'REFRAIN', number: 2 },
    { time: 159, text: 'Pour montrer ma colère et protéger mon corps', type: 'REFRAIN', number: 2 },
    { time: 162, text: 'Je veux garder espoir de déjouer la mort', type: 'REFRAIN', number: 2 },
    { time: 164, text: 'Je ne veux pas qu\'on m\'oublie et qu\'on me déshonore', type: 'REFRAIN', number: 2 },
    { time: 167, text: 'Pour la patrie, j\'ai sacrifié ma vie', type: 'REFRAIN', number: 2 },
    { time: 169, text: 'Pour la nation, je renonce à mon nom', type: 'REFRAIN', number: 2 },
    { time: 172, text: 'Pour les Français, j\'irai jusqu\'au bûcher', type: 'REFRAIN', number: 2 },
    { time: 174, text: 'Et pour ma religion, j\'irai au front', type: 'REFRAIN', number: 2 },
    { time: 179, text: '...', type: 'INSTRUMENTAL', number: 3 },
    { time: 183, text: 'Nous cheminâmes, trois semaines et trois jours', type: 'COUPLET', number: 3 },
    { time: 188, text: 'Nous avons hâte de prouver notre bravoure', type: 'COUPLET', number: 3 },
    { time: 193, text: 'Nous avançons sur le son des tambours', type: 'COUPLET', number: 3 },
    { time: 198, text: 'Pour rendre fier notre leader Zemmour', type: 'COUPLET', number: 3 },
    { time: 203, text: 'Boutons-les hors de notre territoire', type: 'COUPLET', number: 3 },
    { time: 205.5, text: 'Ces étrangers qui volent notre histoire', type: 'COUPLET', number: 3 },
    { time: 208, text: 'Violant nos femmes et pillant nos terroirs', type: 'COUPLET', number: 3 },
    { time: 210, text: 'Nous les jetterons à l\'eau dès ce soir', type: 'COUPLET', number: 3 },
    { time: 213, text: 'Nous avons vaincu ces envahisseurs', type: 'BRIDGE', number: 1 },
    { time: 215.5, text: 'Eux qui étaient originaires d\'ailleurs', type: 'BRIDGE', number: 1 },
    { time: 218, text: 'Mais à présent, Français, n\'ayez plus peur', type: 'BRIDGE', number: 1 },
    { time: 221, text: 'Du peuple, nous sommes les libérateurs', type: 'BRIDGE', number: 1 },
    { time: 226, text: 'Alors je lève le poing haut, franc et fort', type: 'REFRAIN', number: 3 },
    { time: 230, text: 'Pour montrer ma colère et protéger mon corps', type: 'REFRAIN', number: 3 },
    { time: 232, text: 'Je veux garder espoir de déjouer la mort', type: 'REFRAIN', number: 3 },
    { time: 234, text: 'Je ne veux pas qu\'on m\'oublie et qu\'on me déshonore', type: 'REFRAIN', number: 3 },
    { time: 237, text: 'Pour la patrie, j\'ai sacrifié ma vie', type: 'REFRAIN', number: 3 },
    { time: 239, text: 'Pour la nation, je renonce à mon nom', type: 'REFRAIN', number: 3 },
    { time: 242, text: 'Pour les Français, j\'irai jusqu\'au bûcher', type: 'REFRAIN', number: 3 },
    { time: 244, text: 'Et pour ma religion, j\'irai au front', type: 'REFRAIN', number: 3 },
    { time: 249, text: '...', type: 'INSTRUMENTAL', number: 3 },
  ],

  5: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 10, text: 'Pied sur la pédale, je démarre en trombe,', type: 'INTRO', number: 1 },
    { time: 13, text: 'La croupe en arrière, la poitrine en avant,', type: 'INTRO', number: 1 },
    { time: 15, text: 'Est-tu prêt, bébé, à braver et dompter le vent ?', type: 'INTRO', number: 1 },
    { time: 18, text: 'Sur les routes de France je vais faire une hécatombe', type: 'INTRO', number: 1 },
    { time: 23, text: 'Cuir noir partout sur mon corps, moi la motarde,', type: 'REFRAIN', number: 1 },
    { time: 25.5, text: 'J\'fais vibrer les moteurs et les cœurs, baby, yeah, yeah', type: 'REFRAIN', number: 1 },
    { time: 28, text: 'Moi je roule sur les routes et les keufs, baby, yeah yeah', type: 'REFRAIN', number: 1 },
    { time: 31, text: 'C\'est ma vie, vie, baby, j\'roule à fond, fond', type: 'REFRAIN', number: 1 },
    { time: 34, text: 'C\'est ma life, life, chéri chui une motarde', type: 'REFRAIN', number: 1 },
    { time: 36.5, text: 'Tout l\'monde a peur de s\'trouver devant moi,', type: 'COUPLET', number: 1 },
    { time: 39, text: 'Tout l\'monde a peur de s\'trouver hors la loi,', type: 'COUPLET', number: 1 },
    { time: 41.5, text: 'Si tu me vois, tu n\'as rien à faire là,', type: 'COUPLET', number: 1 },
    { time: 44, text: 'Si tu me vois, t\'as qu\'à bouger de là', type: 'COUPLET', number: 1 },
    { time: 47.5, text: 'Hors de question de dévier mon chemin,', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Pour moi vous êtes des esclaves et des chiens', type: 'COUPLET', number: 1 },
    { time: 52, text: 'Qui n\'sont là que pour étancher ma faim.', type: 'COUPLET', number: 1 },
    { time: 55, text: 'Dois-je vous expliquer ou faire un dessin ?', type: 'COUPLET', number: 1 },
    { time: 57, text: 'Je parle bien sûr d\'un hargneux coup de rein,', type: 'COUPLET', number: 1 },
    { time: 60, text: 'Qui foudroie, brise et sectionne mon bassin.', type: 'COUPLET', number: 1 },
    { time: 63, text: 'Cuir noir partout sur mon corps, moi la motarde,', type: 'REFRAIN', number: 2 },
    { time: 65, text: 'J\'fais vibrer les moteurs et les cœurs, baby, yeah, yeah', type: 'REFRAIN', number: 2 },
    { time: 68, text: 'Moi je roule sur les routes et les keufs, baby, yeah yeah', type: 'REFRAIN', number: 2 },
    { time: 70, text: 'C\'est ma vie, vie, baby, j\'roule à fond, fond', type: 'REFRAIN', number: 2 },
    { time: 73, text: 'C\'est ma life, life, chéri chui une motarde', type: 'REFRAIN', number: 2 },
    { time: 77, text: 'Moi dans le lit, sur le lit, je domine,', type: 'COUPLET', number: 2 },
    { time: 79, text: 'Moi à l\'armée je me bats comme je pine,', type: 'COUPLET', number: 2 },
    { time: 82, text: 'Moi attachée je déploie mes babines', type: 'COUPLET', number: 2 },
    { time: 84, text: 'Moi j\'aime à sec, je n\'mets pas de vaz\'line.', type: 'COUPLET', number: 2 },
    { time: 87, text: 'T\'as peur, t\'as dit : « La moto ça va vite ! »', type: 'COUPLET', number: 2 },
    { time: 89, text: 'Mais écoute bien c\'que je dis sur ta bite :', type: 'COUPLET', number: 2 },
    { time: 92, text: '« J\'ai pas peur, je crains pas la vitesse,', type: 'COUPLET', number: 2 },
    { time: 94, text: 'J\'drive comme une femme, je drive comme une déesse,', type: 'COUPLET', number: 2 },
    { time: 97, text: 'Le tout est d\'bien attacher mes petites fesses. »', type: 'COUPLET', number: 2 },
    { time: 100, text: 'J\'te fais peur, mon cœur ? Alors regarde,', type: 'BRIDGE', number: 1 },
    { time: 102, text: 'Attache toi bien, si t\'es là, c\'est pas par mégarde.', type: 'BRIDGE', number: 1 },
    { time: 105, text: 'Quand j\'suis en mission, ils m\'appellent « Flash McQueen »', type: 'BRIDGE', number: 1 },
    { time: 107, text: 'Si je te veux, je te win, win, win.', type: 'BRIDGE', number: 1 },
    { time: 111, text: 'Cuir noir partout sur mon corps, moi la motarde,', type: 'REFRAIN', number: 3 },
    { time: 113, text: 'J\'fais vibrer les moteurs et les cœurs, baby, yeah, yeah', type: 'REFRAIN', number: 3 },
    { time: 116, text: 'Moi je roule sur les routes et les keufs, baby, yeah yeah', type: 'REFRAIN', number: 3 },
    { time: 119, text: 'C\'est ma vie, vie, baby, j\'roule à fond, fond', type: 'REFRAIN', number: 3 },
    { time: 121, text: 'C\'est ma life, life, chéri chui une motarde', type: 'REFRAIN', number: 3 },
    { time: 126, text: 'Cuir noir partout sur mon corps, moi la motarde,', type: 'REFRAIN', number: 4 },
    { time: 128, text: 'J\'fais vibrer les moteurs et les cœurs, baby, yeah, yeah', type: 'REFRAIN', number: 4 },
    { time: 131, text: 'Moi je roule sur les routes et les keufs, baby, yeah yeah', type: 'REFRAIN', number: 4 },
    { time: 134, text: 'C\'est ma vie, vie, baby, j\'roule à fond, fond', type: 'REFRAIN', number: 4 },
    { time: 136, text: 'C\'est ma life, life, chéri chui une motarde', type: 'REFRAIN', number: 4 },
    { time: 141, text: 'Ooh, les moteurs vrombissent et les pneus crissent,', type: 'OUTRO', number: 1 },
    { time: 146, text: 'Ooh, ça te met pas dans l\'mood ? T\'as peur ?', type: 'OUTRO', number: 1 },
    { time: 149, text: 'C\'est pas du vent, baby, chui une motarde.', type: 'OUTRO', number: 1 },
  ],

  6: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 22, text: 'Je pensais que tu perdrais toute humanité,', type: 'COUPLET', number: 1 },
    { time: 25, text: 'Lorsque tu déciderais d\'entrer dans l\'armée.', type: 'COUPLET', number: 1 },
    { time: 27, text: 'Ton expérience a montré que je me trompais,', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Car tu y es entrée, et tu n\'as pas changé.', type: 'COUPLET', number: 1 },
    { time: 32, text: 'J\'haïssais ces cérémonies aux étendards,', type: 'COUPLET', number: 1 },
    { time: 35, text: 'Cett\' fervente déférence à la France impériale,', type: 'COUPLET', number: 1 },
    { time: 38, text: 'Cette mémoire arrangée qui maquille l\'histoire,', type: 'COUPLET', number: 1 },
    { time: 40, text: 'Ce roman national, cett\' fierté coloniale.', type: 'COUPLET', number: 1 },
    { time: 43, text: 'J\'n\'ai retenu qu\'une chose de l\'université', type: 'COUPLET', number: 1 },
    { time: 45, text: 'Que l\'armée permet à l\'État de dominer,', type: 'COUPLET', number: 1 },
    { time: 48, text: 'Qu\'il lui donne le droit de punir, de surveiller,', type: 'COUPLET', number: 1 },
    { time: 51, text: 'De nous discipliner et de nous contrôler.', type: 'COUPLET', number: 1 },
    { time: 53, text: 'Moi, j\'étais conditionnée à en avoir peur', type: 'COUPLET', number: 1 },
    { time: 56, text: 'L\'ordre comme la soumission, je les rejetais', type: 'COUPLET', number: 1 },
    { time: 59, text: 'J\'étais loin d\'imaginer et d\'envisager', type: 'COUPLET', number: 1 },
    { time: 62, text: 'Qu\'ils seraient pour moi des pouvoirs libérateur.', type: 'COUPLET', number: 1 },
    { time: 65, text: 'Mais, mes clichés, tu les as fait mentir.', type: 'REFRAIN', number: 1 },
    { time: 67, text: 'Mais, avec l\'armée, tu m\'réconcilies.', type: 'REFRAIN', number: 1 },
    { time: 70, text: 'Car j\'avoue qu\'un militaire en treillis…', type: 'REFRAIN', number: 1 },
    { time: 74, text: 'C\'est sexy !', type: 'REFRAIN', number: 1 },
    { time: 77, text: 'Donnez moi accès aux corps de l\'armée,', type: 'REFRAIN', number: 1 },
    { time: 80, text: 'Ces corps qui sont bien mieux nus qu\'habillés', type: 'REFRAIN', number: 1 },
    { time: 82, text: 'Car j\'avoue qu\'un militaire sans treillis…', type: 'REFRAIN', number: 1 },
    { time: 84, text: 'C\'est sexy !', type: 'REFRAIN', number: 1 },
    { time: 85, text: 'Tu es partie sûre de toi sans faire volte-face,', type: 'COUPLET', number: 2 },
    { time: 88, text: 'Tu es revenue avec au bras un FAMAS.', type: 'COUPLET', number: 2 },
    { time: 91, text: 'T\'as décidé de faire ta FMIR en plein hiver', type: 'COUPLET', number: 2 },
    { time: 94, text: 'Te forgeant une expérience extraordinaire.', type: 'COUPLET', number: 2 },
    { time: 97, text: 'Mais tu n\'es pas allée à l\'armée que pour toi.', type: 'COUPLET', number: 2 },
    { time: 100, text: 'T\'as pensé à papa, maman, Thibault et moi.', type: 'COUPLET', number: 2 },
    { time: 101.5, text: 'Ce fut mon premier signe de collaboration :', type: 'COUPLET', number: 2 },
    { time: 103, text: 'J\'ai récupéré les rest\' de vos collations', type: 'COUPLET', number: 2 },
    { time: 106, text: 'Chaque fois que tu rentrais d\'une de tes mission,', type: 'COUPLET', number: 2 },
    { time: 109, text: 'Tu nous apportais des cadeaux à la maison.', type: 'COUPLET', number: 2 },
    { time: 112, text: 'Ça a commencé avec des soupes, des bonbon,', type: 'COUPLET', number: 2 },
    { time: 114, text: 'Et puis un jour tu m\'as amenée trois garçons.', type: 'COUPLET', number: 2 },
    { time: 116, text: 'Ce fut trois militaires aux physiques magnifiques,', type: 'COUPLET', number: 2 },
    { time: 120, text: 'Et pourtant à la pensée si phallocentrique.', type: 'COUPLET', number: 2 },
    { time: 121, text: 'Malgré tout, avec eux trois tu m\'as convaincue,', type: 'COUPLET', number: 2 },
    { time: 123, text: 'A l\'armée, je ne m\'opposerai jamais plus.', type: 'COUPLET', number: 2 },
    { time: 129, text: 'Attends… ne suis-je pas une gaucho ?', type: 'BRIDGE', number: 1 },
    { time: 131, text: 'Ne suis-je pas censée m\'opposer', type: 'BRIDGE', number: 1 },
    { time: 134, text: 'Au monopole de la violence physique légitime ?', type: 'BRIDGE', number: 1 },
    { time: 139, text: 'Je crois que je me suis égarée,', type: 'BRIDGE', number: 1 },
    { time: 143, text: 'Je suis en train de faire une erreur gravissime…', type: 'BRIDGE', number: 1 },
    { time: 150, text: 'Mais, mes clichés, tu les as fait mentir.', type: 'REFRAIN', number: 2 },
    { time: 153, text: 'Mais, avec l\'armée, tu m\'réconcilies.', type: 'REFRAIN', number: 2 },
    { time: 155, text: 'Car j\'avoue qu\'un militaire en treillis…', type: 'REFRAIN', number: 2 },
    { time: 158, text: 'C\'est sexy !', type: 'REFRAIN', number: 2 },
    { time: 160, text: 'Donnez moi accès aux corps de l\'armée,', type: 'REFRAIN', number: 2 },
    { time: 164, text: 'Ces corps qui sont bien mieux nus qu\'habillés', type: 'REFRAIN', number: 2 },
    { time: 166, text: 'Car j\'avoue qu\'un militaire sans treillis…', type: 'REFRAIN', number: 2 },
    { time: 169, text: 'C\'est sexy !', type: 'REFRAIN', number: 2 },
    { time: 172, text: 'Au bûcher les antimilitaristes !', type: 'REFRAIN', number: 3 },
    { time: 174, text: 'J\'aime l\'esthétique collaborationniste !', type: 'REFRAIN', number: 3 },
    { time: 177, text: 'Car j\'avoue qu\'un militaire en treillis…', type: 'REFRAIN', number: 3 },
    { time: 180, text: 'C\'est sexy !', type: 'REFRAIN', number: 3 },
    { time: 182, text: 'Je deviendrais même totalitariste,', type: 'REFRAIN', number: 3 },
    { time: 184, text: 'Si en échange on m\'offre un réserviste.', type: 'REFRAIN', number: 3 },
    { time: 187, text: 'Car j\'avoue qu\'un militaire sans treillis…', type: 'REFRAIN', number: 3 },
    { time: 189, text: 'C\'est sexy !', type: 'REFRAIN', number: 3 },
    { time: 190, text: '...', type: 'INSTRUMENTAL', number: 1 },
  ],

  7: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 11, text: 'Il est temps de conter une histoire', type: 'COUPLET', number: 1 },
    { time: 14, text: 'L\'histoire d\'un regret qui ronge mon cœur.', type: 'COUPLET', number: 1 },
    { time: 16, text: 'Je ne peux me défaire de mes larmes et mes pleurs', type: 'COUPLET', number: 1 },
    { time: 19, text: 'Qui m\'empêchent de vivre et de dormir le soir.', type: 'COUPLET', number: 1 },
    { time: 22, text: 'Chaque nuit les ténèbres emprisonnent mon corps.', type: 'COUPLET', number: 1 },
    { time: 25, text: 'Elles me font souffrir jusqu\'à souhaiter la mort.', type: 'COUPLET', number: 1 },
    { time: 27, text: 'Je m\'en veux de ne pas les avoir regardé', type: 'COUPLET', number: 1 },
    { time: 29, text: 'Ces trois beaux militaires qui devant moi se déshabillaient.', type: 'COUPLET', number: 1 },
    { time: 32, text: 'Alors je m\'assois à l\'abri des grand chênes,', type: 'COUPLET', number: 1 },
    { time: 34, text: 'Pour espérer soigner mon chagrin et ma peine.', type: 'COUPLET', number: 1 },
    { time: 36, text: 'Je m\'assois dans ce parc si proche de l\'Arsenal,', type: 'COUPLET', number: 1 },
    { time: 39, text: 'Me lamentant de ne pouvoir pousser la porte Royale.', type: 'COUPLET', number: 1 },
    { time: 42, text: 'Devant moi les feuilles s\'envolent, en moi le manque grandit.', type: 'COUPLET', number: 1 },
    { time: 44, text: 'Devant moi l\'automne pleure, et en moi le froid rugit.', type: 'COUPLET', number: 1 },
    { time: 48, text: 'Les arbres rougissent de mon désir inassouvi.', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Pourquoi n\'ai-je dit mot, n\'ai-je fait geste pour les retenir ?', type: 'COUPLET', number: 1 },
    { time: 53, text: 'Assise sur ce banc face aux larges murs de pierre,', type: 'BRIDGE', number: 1 },
    { time: 56, text: 'Je prends une inspiration et chante ma prière...', type: 'BRIDGE', number: 1 },
    { time: 59, text: 'Et le vent et le froid envahissent mes pensées', type: 'REFRAIN', number: 1 },
    { time: 61, text: 'Car vous seriez si beaux si votre uniforme tombait.', type: 'REFRAIN', number: 1 },
    { time: 64, text: 'Et mon désir si brûlant chaufferait la Citadelle,', type: 'REFRAIN', number: 1 },
    { time: 67, text: 'Si pendant un moment vous montriez vos chandelles.', type: 'REFRAIN', number: 1 },
    { time: 69, text: 'Et la peur et l\'effroi me transpercent le cœur', type: 'REFRAIN', number: 1 },
    { time: 72, text: 'À l\'idée de ne pouvoir jamais toucher vos corps.', type: 'REFRAIN', number: 1 },
    { time: 75, text: 'Devrais-je bénir ou maudire ma sœur', type: 'REFRAIN', number: 1 },
    { time: 78, text: 'Qui a tissé mes soirées d\'un fil de remords ?', type: 'REFRAIN', number: 1 },
    { time: 89, text: 'Gabrielle, qu\'elle idée as-tu eue ?', type: 'COUPLET', number: 2 },
    { time: 92, text: 'Voir ces Apollons n\'étaient pas prévu :', type: 'COUPLET', number: 2 },
    { time: 95, text: 'Mon regard a fui et s\'est perdu,', type: 'COUPLET', number: 2 },
    { time: 98, text: 'Et rêve chaque soir de les voir nus.', type: 'COUPLET', number: 2 },
    { time: 100, text: 'Fraîchement entré', type: 'COUPLET', number: 2 },
    { time: 101, text: 'Le premier m\'a subjuguée', type: 'COUPLET', number: 2 },
    { time: 103, text: 'On eu dit un dieu', type: 'COUPLET', number: 2 },
    { time: 104, text: 'Rayonnant de mille feux.', type: 'COUPLET', number: 2 },
    { time: 106, text: 'En vérité je ne pu bien le voir car', type: 'COUPLET', number: 2 },
    { time: 108, text: 'Noir était le couloir à mon grand désespoir.', type: 'COUPLET', number: 2 },
    { time: 111, text: 'Totalement démunie et dégoûtée j\'étais, car', type: 'COUPLET', number: 2 },
    { time: 113, text: 'l\'Interrupteur, jamais nous ne l\'avons trouvé', type: 'COUPLET', number: 2 },
    { time: 116, text: 'Nous empêchant de voir son corps parfait.', type: 'COUPLET', number: 2 },
    { time: 119, text: 'Ce deuxième gars', type: 'COUPLET', number: 2 },
    { time: 121, text: 'Y-a-t\'il la possibilité de le toucher ?', type: 'COUPLET', number: 2 },
    { time: 124, text: 'Ruisselant de sueur et de beauté,', type: 'COUPLET', number: 2 },
    { time: 126, text: 'Imaginez simplement qu\'il avait', type: 'COUPLET', number: 2 },
    { time: 129, text: 'La bite « grande comme ça ».', type: 'COUPLET', number: 2 },
    { time: 132, text: 'Miam, miam ! Voici l\'ambroisie, le Graal', type: 'COUPLET', number: 2 },
    { time: 135, text: 'Objectivement un dieu grec idéal :', type: 'COUPLET', number: 2 },
    { time: 137, text: 'Radieux comme un antique héro,', type: 'COUPLET', number: 2 },
    { time: 139, text: 'Galactique au lit comme un Gémeau,', type: 'COUPLET', number: 2 },
    { time: 140, text: 'Addictif comme de la nicotine.', type: 'COUPLET', number: 2 },
    { time: 142, text: 'Nulle doute : pour lui je serai sanguine.', type: 'COUPLET', number: 2 },
    { time: 149, text: 'Assise sur ce banc face aux larges murs de pierre,', type: 'BRIDGE', number: 2 },
    { time: 151, text: 'Je prends une inspiration et chante ma prière...', type: 'BRIDGE', number: 2 },
    { time: 154, text: 'Et le vent et le froid envahissent mes pensées', type: 'REFRAIN', number: 2 },
    { time: 157, text: 'Car vous seriez si beaux si votre uniforme tombait.', type: 'REFRAIN', number: 2 },
    { time: 159, text: 'Et mon désir si brûlant chaufferait la Citadelle,', type: 'REFRAIN', number: 2 },
    { time: 162, text: 'Si pendant un moment vous montriez vos chandelles.', type: 'REFRAIN', number: 2 },
    { time: 165, text: 'Et la peur et l\'effroi me transpercent le cœur', type: 'REFRAIN', number: 2 },
    { time: 167, text: 'À l\'idée de ne pouvoir jamais toucher vos corps.', type: 'REFRAIN', number: 2 },
    { time: 170, text: 'Devrais-je bénir ou maudire ma sœur', type: 'REFRAIN', number: 2 },
    { time: 173, text: 'Qui a tissé mes soirées d\'un fil de remords ?', type: 'REFRAIN', number: 2 },
    { time: 179, text: '...', type: 'INSTRUMENTAL', number: 2 },
    { time: 207, text: 'Et le vent et le froid envahissent mes pensées', type: 'REFRAIN', number: 3 },
    { time: 209, text: 'Car vous seriez si beaux si votre uniforme tombait.', type: 'REFRAIN', number: 3 },
    { time: 211, text: 'Et mon désir si brûlant chaufferait la Citadelle,', type: 'REFRAIN', number: 3 },
    { time: 213, text: 'Si pendant un moment vous montriez vos chandelles.', type: 'REFRAIN', number: 3 },
    { time: 215, text: 'Et la peur et l\'effroi me transpercent le cœur', type: 'REFRAIN', number: 3 },
    { time: 217, text: 'À l\'idée de ne pouvoir jamais toucher vos corps.', type: 'REFRAIN', number: 3 },
    { time: 219, text: 'Devrais-je bénir ou maudire ma sœur', type: 'REFRAIN', number: 3 },
    { time: 221, text: 'Qui a tissé mes soirées d\'un fil de remords ?', type: 'REFRAIN', number: 3 },
    { time: 223, text: 'Et le vent et le froid envahissent mes pensées', type: 'REFRAIN', number: 4 },
    { time: 225, text: 'Car vous seriez si beaux si votre uniforme tombait.', type: 'REFRAIN', number: 4 },
    { time: 227, text: 'Et mon désir si brûlant chaufferait la Citadelle,', type: 'REFRAIN', number: 4 },
    { time: 229, text: 'Si pendant un moment vous montriez vos chandelles.', type: 'REFRAIN', number: 4 },
    { time: 231, text: 'Et la peur et l\'effroi me transpercent le cœur', type: 'REFRAIN', number: 4 },
    { time: 233, text: 'À l\'idée de ne pouvoir jamais toucher vos corps.', type: 'REFRAIN', number: 4 },
    { time: 237, text: 'Devrais-je bénir ou maudire ma sœur', type: 'REFRAIN', number: 4 },
    { time: 241, text: 'Qui a tissé mes soirées d\'un fil de remords ?', type: 'REFRAIN', number: 4 },
  ],

  8: [
    { time: 0, text: 'Hey !', type: 'INTRO', number: 1 },
    { time: 5, text: 'Hey ! Hey !', type: 'INTRO', number: 1 },
    { time: 11, text: 'Hey !', type: 'INTRO', number: 1 },
    { time: 12, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 1 },
    { time: 14, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 1 },
    { time: 15, text: 'T\'as pris un an dans le trou du cul', type: 'REFRAIN', number: 1 },
    { time: 17, text: 'J\'espère au moins que ça t\'a plu', type: 'REFRAIN', number: 1 },
    { time: 19, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 1 },
    { time: 20, text: 'Qu\'on fête tous ça comme des champions', type: 'REFRAIN', number: 1 },
    { time: 22, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 1 },
    { time: 23, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 1 },
    { time: 25, text: 'T\'as pris un an dans la marchandise', type: 'REFRAIN', number: 1 },
    { time: 27, text: 'Faut pas que ça te traumatise', type: 'REFRAIN', number: 1 },
    { time: 28, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 1 },
    { time: 30, text: 'Qu\'on fête tout ça comme des champions', type: 'REFRAIN', number: 1 },
    { time: 31, text: 'Hey !', type: 'INSTRUMENTAL', number: 1 },
    { time: 34, text: 'Hey !', type: 'INSTRUMENTAL', number: 1 },
    { time: 37, text: 'Comme des champions', type: 'INSTRUMENTAL', number: 1 },
    { time: 38, text: 'Hey !', type: 'INSTRUMENTAL', number: 1 },
    { time: 41, text: 'Hey !', type: 'INSTRUMENTAL', number: 1 },
    { time: 43, text: 'Comme des champions', type: 'INSTRUMENTAL', number: 1 },
    { time: 44, text: 'Tant que la bête est vigoureuse', type: 'COUPLET', number: 1 },
    { time: 46, text: 'Ta vie sera toujours heureuse', type: 'COUPLET', number: 1 },
    { time: 47, text: 'Attention aux grosses maladies', type: 'COUPLET', number: 1 },
    { time: 49, text: 'Faut pas choper de saloperies', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Remplis les verres on est sincères', type: 'COUPLET', number: 1 },
    { time: 52, text: 'C\'est ton putain d\'anniversaire', type: 'COUPLET', number: 1 },
    { time: 54, text: 'Alors s\'te plaît paies ta tournée', type: 'COUPLET', number: 1 },
    { time: 55, text: 'Sinon tu devras nous rembourser', type: 'COUPLET', number: 1 },
    { time: 58, text: 'Hey ! Hey !', type: 'INSTRUMENTAL', number: 2 },
    { time: 60, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 2 },
    { time: 62, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 2 },
    { time: 63, text: 'T\'as pris un an dans le trou du cul', type: 'REFRAIN', number: 2 },
    { time: 65, text: 'J\'espère au moins que ça t\'a plu', type: 'REFRAIN', number: 2 },
    { time: 67, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 2 },
    { time: 68, text: 'Qu\'on fête tous ça comme des champions', type: 'REFRAIN', number: 2 },
    { time: 70, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 2 },
    { time: 71, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 2 },
    { time: 73, text: 'T\'as pris un an dans la marchandise', type: 'REFRAIN', number: 2 },
    { time: 75, text: 'Faut pas que ça te traumatise', type: 'REFRAIN', number: 2 },
    { time: 76, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 2 },
    { time: 78, text: 'Qu\'on fête tout ça comme des champions', type: 'REFRAIN', number: 2 },
    { time: 79, text: 'Ouais ! Ouais !', type: 'INSTRUMENTAL', number: 3 },
    { time: 82, text: 'Ouais !', type: 'INSTRUMENTAL', number: 3 },
    { time: 83, text: 'Comme des champions', type: 'INSTRUMENTAL', number: 3 },
    { time: 86, text: 'Ouais !', type: 'INSTRUMENTAL', number: 3 },
    { time: 89, text: 'Ouais !', type: 'INSTRUMENTAL', number: 3 },
    { time: 92, text: 'Ouais ! Ouais !', type: 'INSTRUMENTAL', number: 3 },
    { time: 93, text: 'Encore trois soixante-cinq chaque jour', type: 'COUPLET', number: 2 },
    { time: 95, text: 'Wop ! Wop !', type: 'COUPLET', number: 2 },
    { time: 96, text: 'Et c\'est reparti pour un p\'tit tour', type: 'COUPLET', number: 2 },
    { time: 98, text: 'Wop ! Wop !', type: 'COUPLET', number: 2 },
    { time: 99, text: 'Tu sais tu peux compter sur nous', type: 'COUPLET', number: 2 },
    { time: 101, text: 'Wop ! Wop !', type: 'COUPLET', number: 2 },
    { time: 102, text: 'Il y a toujours une place chez les fous', type: 'COUPLET', number: 2 },
    { time: 104, text: 'Wop ! Wop !', type: 'COUPLET', number: 2 },
    { time: 105, text: 'Essaie de nous rendre tous joyeux', type: 'COUPLET', number: 2 },
    { time: 107, text: 'Wop ! Wop !', type: 'COUPLET', number: 2 },
    { time: 108, text: 'Et fais c\'que tu sais faire de mieux', type: 'COUPLET', number: 2 },
    { time: 113, text: 'Ouais ! Ouais !', type: 'INSTRUMENTAL', number: 4 },
    { time: 114, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 3 },
    { time: 116, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 3 },
    { time: 118, text: 'T\'as pris un an dans le trou du cul', type: 'REFRAIN', number: 3 },
    { time: 119, text: 'J\'espère au moins que ça t\'a plu', type: 'REFRAIN', number: 3 },
    { time: 121, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 3 },
    { time: 122, text: 'Qu\'on fête tous ça comme des champions', type: 'REFRAIN', number: 3 },
    { time: 124, text: 'Bon anniversaire la grosse cochonne', type: 'REFRAIN', number: 3 },
    { time: 126, text: 'Fais attention à ton rectum', type: 'REFRAIN', number: 3 },
    { time: 127, text: 'T\'as pris un an dans la marchandise', type: 'REFRAIN', number: 3 },
    { time: 129, text: 'Faut pas que ça te traumatise', type: 'REFRAIN', number: 3 },
    { time: 130, text: 'Allez grosse pute c\'est ta chanson', type: 'REFRAIN', number: 3 },
    { time: 132, text: 'Qu\'on fête tout ça comme des champions', type: 'REFRAIN', number: 3 },
    { time: 134, text: 'Ouais ! Ouais ! Ouais !', type: 'OUTRO', number: 1 },
  ],

  9: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 23, text: 'Je me lève enchanté', type: 'COUPLET', number: 1 },
    { time: 27, text: 'Pour aller voter ce phénomène', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Je me lève émerveillé', type: 'COUPLET', number: 1 },
    { time: 33, text: 'Pour aller voter le RN', type: 'COUPLET', number: 1 },
    { time: 36, text: 'Et au fond des présentoirs', type: 'COUPLET', number: 1 },
    { time: 41, text: 'Que des papiers sans importance', type: 'COUPLET', number: 1 },
    { time: 44, text: 'Uniquement un seul dans l\'isoloir', type: 'COUPLET', number: 1 },
    { time: 50, text: 'Tout le reste dans l\'urinoir', type: 'COUPLET', number: 1 },
    { time: 52, text: 'Je saurais entendre vos avis', type: 'COUPLET', number: 1 },
    { time: 57, text: 'Mettre trop de gens dans l\'ignorance', type: 'COUPLET', number: 1 },
    { time: 60, text: 'Aussi fort que les nazis', type: 'COUPLET', number: 1 },
    { time: 62, text: 'Aussi fier que les néo-nazis', type: 'COUPLET', number: 1 },
    { time: 67, text: 'Je me lève enchanté', type: 'REFRAIN', number: 1 },
    { time: 71, text: 'Pour aller voter ce phénomène', type: 'REFRAIN', number: 1 },
    { time: 74, text: 'Je me lève émerveillé', type: 'REFRAIN', number: 1 },
    { time: 77, text: 'Pour aller voter le RN', type: 'REFRAIN', number: 1 },
    { time: 82, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 89, text: 'En sortant de l\'isoloir', type: 'COUPLET', number: 2 },
    { time: 91, text: 'Aussi fier qu\'un jaguar', type: 'COUPLET', number: 2 },
    { time: 92, text: 'D\'avoir rien mis dans la poubelle', type: 'COUPLET', number: 2 },
    { time: 96, text: 'Les écolos prenaient-en de la graine', type: 'COUPLET', number: 2 },
    { time: 98, text: 'On me crie à la face "A voter !"', type: 'COUPLET', number: 2 },
    { time: 101, text: 'Moi je ris au nez "A élire !"', type: 'COUPLET', number: 2 },
    { time: 104, text: 'Ce que j\'adore c\'est provoquer', type: 'COUPLET', number: 2 },
    { time: 106, text: 'Ce que j\'adore c\'est conquérir', type: 'COUPLET', number: 2 },
    { time: 113, text: 'Je me lève enchanté', type: 'REFRAIN', number: 2 },
    { time: 116, text: 'Pour aller voter ce phénomène', type: 'REFRAIN', number: 2 },
    { time: 119, text: 'Je me lève émerveillé', type: 'REFRAIN', number: 2 },
    { time: 122, text: 'Pour aller voter le RN', type: 'REFRAIN', number: 2 },
    { time: 129, text: 'Ringot ne fait pas le poids face à ce beau Jean-Baptiste Garde', type: 'BRIDGE', number: 1 },
    { time: 132, text: 'Ancien militaire ma foi le grand remplacement ça tarde', type: 'BRIDGE', number: 1 },
    { time: 135, text: 'Avant 2027 il y a 2026', type: 'BRIDGE', number: 1 },
    { time: 138, text: 'Ça sera un peu le synopsis', type: 'BRIDGE', number: 1 },
    { time: 140, text: 'De notre future présidence', type: 'BRIDGE', number: 1 },
    { time: 143, text: 'De notre future délivrance', type: 'BRIDGE', number: 1 },
    { time: 150, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 154, text: 'Je me lève enchanté', type: 'REFRAIN', number: 3 },
    { time: 156, text: 'Pour aller voter ce phénomène', type: 'REFRAIN', number: 3 },
    { time: 159, text: 'Je me lève émerveillé', type: 'REFRAIN', number: 3 },
    { time: 162, text: 'Pour aller voter... le RN', type: 'REFRAIN', number: 3 },
    { time: 170, text: 'Je me lève enchanté', type: 'OUTRO', number: 1 },
    { time: 174, text: 'Pour aller voter ce phénomène', type: 'OUTRO', number: 1 },
    { time: 180, text: 'Je me lève émerveillé', type: 'OUTRO', number: 3 },
    { time: 187, text: 'Pour aller voter... le RN', type: 'OUTRO', number: 3 },
    { time: 196, text: '...', type: 'INSTRUMENTAL', number: 1 },
    
  ],

  101: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 7, text: 'C\'est la belle nuit de Noël', type: 'COUPLET', number: 1 },
    { time: 10, text: 'Ma lance est dans son manteau blanc', type: 'COUPLET', number: 1 },
    { time: 15, text: 'Et mon gland levé vers le ciel', type: 'COUPLET', number: 1 },
    { time: 18, text: 'A genoux les demandant', type: 'COUPLET', number: 1 },
    { time: 22, text: 'Avant de fermer les paupières', type: 'COUPLET', number: 1 },
    { time: 26, text: 'Buvons une dernière bière', type: 'COUPLET', number: 1 },
    { time: 29, text: 'Petit papa Noël', type: 'REFRAIN', number: 1 },
    { time: 32, text: 'Quand tu descendras du ciel', type: 'REFRAIN', number: 1 },
    { time: 36, text: 'Avec des dildos par milliers', type: 'REFRAIN', number: 1 },
    { time: 40, text: 'N\'oublie pas mon petit gode michet', type: 'REFRAIN', number: 1 },
    { time: 44, text: 'Mais avant de partir', type: 'COUPLET', number: 2 },
    { time: 47, text: 'Il faudra bien me faire jouir', type: 'COUPLET', number: 2 },
    { time: 51, text: 'Tu n\'as qu\'à penser à Gaïa', type: 'COUPLET', number: 2 },
    { time: 55, text: 'Pour la mettre au fond de moi', type: 'COUPLET', number: 2 },
    { time: 59, text: 'Il me tarde tant que le jour se lève', type: 'COUPLET', number: 2 },
    { time: 63, text: 'Pour voir si tu m\'as inséré', type: 'COUPLET', number: 2 },
    { time: 66, text: 'Tous les beaux joujous que je vois en rêve', type: 'COUPLET', number: 2 },
    { time: 70, text: 'Et que je t\'ai commandé', type: 'COUPLET', number: 2 },
    { time: 74, text: 'Petit papa Noël', type: 'REFRAIN', number: 2 },
    { time: 77, text: 'Quand tu descendras du ciel', type: 'REFRAIN', number: 2 },
    { time: 81, text: 'Avec des dildos par milliers', type: 'REFRAIN', number: 2 },
    { time: 85, text: 'N\'oublie pas mon petit gode michet', type: 'REFRAIN', number: 2 },
    { time: 104, text: 'Le roumain est passé', type: 'COUPLET', number: 3 },
    { time: 108, text: 'Certains vont se faire sodo', type: 'COUPLET', number: 3 },
    { time: 112, text: 'Et tu vas pouvoir commencer', type: 'COUPLET', number: 3 },
    { time: 115, text: 'Avec ta capote sur le barreau', type: 'COUPLET', number: 3 },
    { time: 119, text: 'Au son des cloches des églises', type: 'COUPLET', number: 3 },
    { time: 123, text: 'Les prêtres auront une surprise', type: 'COUPLET', number: 3 },
    { time: 127, text: 'Et quand tu gicleras sur mon visage', type: 'COUPLET', number: 3 },
    { time: 131, text: 'C\'est comme ça que nous baiserons', type: 'COUPLET', number: 3 },
    { time: 134, text: 'Je n\'ai pas été tous les jours très sage', type: 'COUPLET', number: 3 },
    { time: 138, text: 'Punis-moi pour mon pardon', type: 'COUPLET', number: 3 },
    { time: 141, text: 'Petit papa Noël', type: 'REFRAIN', number: 3 },
    { time: 145, text: 'Quand tu descendras du ciel', type: 'REFRAIN', number: 3 },
    { time: 149, text: 'Avec des dildos par milliers', type: 'REFRAIN', number: 3 },
    { time: 153, text: 'N\'oublie pas mon petit gode michet', type: 'REFRAIN', number: 3 },
    { time: 156, text: 'Petit papa Noël', type: 'REFRAIN', number: 3 },
  ],
  102: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 14, text: 'Douce nuit, sainte nuit,', type: 'COUPLET', number: 1 },
    { time: 19, text: 'Dans mon lit, l\'astre luit', type: 'COUPLET', number: 1 },
    { time: 24, text: 'Du haut de son centimètre,', type: 'COUPLET', number: 1 },
    { time: 29, text: 'Il aimerait bien lui mettre', type: 'COUPLET', number: 1 },
    { time: 32, text: 'C\'est l\'amour infini, c\'est l\'amour infini', type: 'COUPLET', number: 1 },
    { time: 40, text: 'Saint-Soldat, Saint barreau', type: 'COUPLET', number: 2 },
    { time: 44, text: 'Qu\'il est grand, qu\'il est beau', type: 'COUPLET', number: 2 },
    { time: 48, text: 'Il aimerait bien se faire sauter', type: 'COUPLET', number: 2 },
    { time: 52, text: 'Mais toujours au fond de son tombeau', type: 'COUPLET', number: 2 },
    { time: 56, text: 'Vers son humble berceau, vers son humble berceau', type: 'COUPLET', number: 2 },
    { time: 64, text: 'Oh là là, qu\'il est court', type: 'COUPLET', number: 3 },
    { time: 68, text: 'Il faudra que je la bourre', type: 'COUPLET', number: 3 },
    { time: 72, text: 'Je ne ferai pas de gros détour', type: 'COUPLET', number: 3 },
    { time: 76, text: 'Je ne ferai pas de demi-tour', type: 'COUPLET', number: 3 },
    { time: 80, text: 'Comme la dinde de Noël Comme la dinde de Noël', type: 'COUPLET', number: 3 },
    { time: 88, text: 'C\'est fini, j\'ai joui', type: 'COUPLET', number: 4 },
    { time: 92, text: 'Tout au fond de mon lit', type: 'COUPLET', number: 4 },
    { time: 96, text: 'Mère Noël, est-ce que tu es contente', type: 'COUPLET', number: 4 },
    { time: 100, text: 'Tu me le disais, je suis partante', type: 'COUPLET', number: 4 },
    { time: 104, text: 'Et cela depuis mille ans Et cela depuis mille ans', type: 'COUPLET', number: 4 }, 
    { time: 112, text: 'Je suis prête pour la tournée', type: 'COUPLET', number: 5 },
    { time: 116, text: 'Mère Noël, je reviendrai', type: 'COUPLET', number: 5 },
    { time: 120, text: 'Prend soin de mes lutins préférés', type: 'COUPLET', number: 5 },
    { time: 124, text: 'Ils ont besoin de se masturber', type: 'COUPLET', number: 5 },
    { time: 128, text: 'Ils ne l\'ont pas fait durant une année', type: 'COUPLET', number: 5 },
    { time: 132, text: 'Ils ne l\'ont pas fait durant une année', type: 'COUPLET', number: 5 },
  ],
  103: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 3, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 1 },
    { time: 7, text: 'Tous à poil et on se caresse', type: 'REFRAIN', number: 1 },
    { time: 11, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 1 },
    { time: 15, text: 'Venez tous avant qu\'il se rabaisse', type: 'REFRAIN', number: 1 },
    { time: 18, text: 'Pour Noël j\'ai pris du Viagra', type: 'COUPLET', number: 1 },
    { time: 22, text: 'Mais j\'ai peur de lever la table', type: 'COUPLET', number: 1 },
    { time: 26, text: 'Pour Noël j\'ai pris du Viagra', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Mais elle n\'est pas si redoutable', type: 'COUPLET', number: 1 },
    { time: 33, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 2 },
    { time: 37, text: 'Tous à poil et on se caresse', type: 'REFRAIN', number: 2 },
    { time: 41, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 2 },
    { time: 45, text: 'Venez tous avant qu\'il se rabaisse', type: 'REFRAIN', number: 2 },
    { time: 49, text: 'J\'ai hâte d\'ouvrir mon cadeau', type: 'COUPLET', number: 2 },
    { time: 53, text: 'Mais faut attendre le gateau', type: 'COUPLET', number: 2 },
    { time: 57, text: 'J\'ai hâte d\'ouvrir mon cadeau', type: 'COUPLET', number: 2 },
    { time: 60, text: 'Pour voir si j\'ai eu mon vibro', type: 'COUPLET', number: 2 },
    { time: 64, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 3 },
    { time: 68, text: 'Tous à poil et on se caresse', type: 'REFRAIN', number: 3 },
    { time: 72, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 3 },
    { time: 76, text: 'Venez tous avant qu\'il se rabaisse', type: 'REFRAIN', number: 3 },
    { time: 79, text: 'Partez ! Il faut que je l\'essaie', type: 'COUPLET', number: 3 },
    { time: 83, text: 'Pour voir si je peux faire la fête', type: 'COUPLET', number: 3 },
    { time: 87, text: 'Partez ! Il faut que je l\'essaie', type: 'COUPLET', number: 3 },
    { time: 91, text: 'Je voudrais le faire en cachette', type: 'COUPLET', number: 3 },
    { time: 94, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 4 },
    { time: 98, text: 'Tous à poil et on se caresse', type: 'REFRAIN', number: 4 },
    { time: 102, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 4 },
    { time: 106, text: 'Venez tous avant qu\'il se rabaisse', type: 'REFRAIN', number: 4 },
    { time: 109, text: 'Oh Jésus, oh roi tout puissant', type: 'COUPLET', number: 4 },
    { time: 113, text: 'Pourrais-tu te réincarner ?', type: 'COUPLET', number: 4 },
    { time: 117, text: 'Oh Jésus, oh roi tout puissant', type: 'COUPLET', number: 4 },
    { time: 121, text: 'Prends contrôle de mon gode michet !', type: 'COUPLET', number: 4 },
    { time: 125, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 5 },
    { time: 129, text: 'Tous à poil et on se caresse', type: 'REFRAIN', number: 5 },
    { time: 133, text: 'Il est levé le divin soldat', type: 'REFRAIN', number: 5 },
    { time: 137, text: 'Venez tous avant qu\'il se rabaisse', type: 'REFRAIN', number: 5 },
    { time: 141, text: '...', type: 'INSTRUMENTAL', number: 5 },
  ],
  104: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 13, text: 'Mon beau gros sexe, roi adoré', type: 'COUPLET', number: 1 },
    { time: 16, text: 'Qu\'il aime bien ta rayure', type: 'COUPLET', number: 1 },
    { time: 20, text: 'Quand par l\'hiver il disparaît', type: 'COUPLET', number: 1 },
    { time: 23, text: 'Avec le froid désespéré', type: 'COUPLET', number: 1 },
    { time: 26, text: 'Mon beau gros sexe, roi adoré', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Tu perds ta carrure', type: 'COUPLET', number: 1 },
    { time: 33, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 1 },
    { time: 36, text: 'Mon cadeau est arrivé.', type: 'REFRAIN', number: 1 },
    { time: 40, text: 'Mamie a eu un godmichet,', type: 'REFRAIN', number: 1 },
    { time: 43, text: 'Et c\'est pareil pour notre pépé.', type: 'REFRAIN', number: 1 },
    { time: 46, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 1 },
    { time: 50, text: 'Mon cadeau est employé.', type: 'REFRAIN', number: 1 },
    { time: 57, text: 'Celui de Louis, il est tout mou,', type: 'COUPLET', number: 2 },
    { time: 61, text: 'Bien qu\'il soit toujours en l\'air.', type: 'COUPLET', number: 2 },
    { time: 65, text: 'Petit zizi, tout petit bout,', type: 'COUPLET', number: 2 },
    { time: 68, text: 'Et ses guirlandes et ses joujoux.', type: 'COUPLET', number: 2 },
    { time: 71, text: 'Celui de Louis, il est tout mou,', type: 'COUPLET', number: 2 },
    { time: 75, text: 'Il n\'a jamais fait la guerre.', type: 'COUPLET', number: 2 },
    { time: 78, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 2 },
    { time: 81, text: 'Mon cadeau est arrivé.', type: 'REFRAIN', number: 2 },
    { time: 86, text: 'Mamie a eu un godmichet,', type: 'REFRAIN', number: 2 },
    { time: 89, text: 'Et c\'est pareil pour notre pépé.', type: 'REFRAIN', number: 2 },
    { time: 92, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 2 },
    { time: 95, text: 'Mon cadeau est employé.', type: 'REFRAIN', number: 2 },
    { time: 104, text: 'Mon beau gros sexe, ton grand sommet,', type: 'COUPLET', number: 3 },
    { time: 108, text: 'Et son fidèle ombrage,', type: 'COUPLET', number: 3 },
    { time: 111, text: 'À côté de celui des autres,', type: 'COUPLET', number: 3 },
    { time: 114, text: 'Qui n\'a jamais touché leur côte.', type: 'COUPLET', number: 3 },
    { time: 117, text: 'Mon beau gros sexe, ton grand sommet,', type: 'COUPLET', number: 3 },
    { time: 121, text: 'Il est en plein raffinage.', type: 'COUPLET', number: 3 },
    { time: 124, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 3 },
    { time: 128, text: 'Mon cadeau est arrivé.', type: 'REFRAIN', number: 3 },
    { time: 131, text: 'Mamie a eu un godmichet,', type: 'REFRAIN', number: 3 },
    { time: 134, text: 'Et c\'est pareil pour notre pépé.', type: 'REFRAIN', number: 3 },
    { time: 137, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 3 },
    { time: 141, text: 'Mon cadeau est employé.', type: 'REFRAIN', number: 3 },
    { time: 149, text: 'Celui de Lucas, il ne bouge pas,', type: 'COUPLET', number: 4 },
    { time: 153, text: 'C\'est un personnage passif.', type: 'COUPLET', number: 4 },
    { time: 156, text: 'Malgré le froid, elle ne bouge pas,', type: 'COUPLET', number: 4 },
    { time: 160, text: 'Qu\'il y ait Louis ou bien Gaïa.', type: 'COUPLET', number: 4 },
    { time: 163, text: 'Celui de Lucas, il ne bouge pas,', type: 'COUPLET', number: 4 },
    { time: 166, text: 'C\'est un personnage non actif.', type: 'COUPLET', number: 4 },
    { time: 170, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 4 },
    { time: 173, text: 'Mon cadeau est arrivé.', type: 'REFRAIN', number: 4 },
    { time: 176, text: 'Mamie a eu un godmichet,', type: 'REFRAIN', number: 4 },
    { time: 180, text: 'Et c\'est pareil pour notre pépé.', type: 'REFRAIN', number: 4 },
    { time: 183, text: 'Quand vient Noël, tout décoré,', type: 'REFRAIN', number: 4 },
    { time: 187, text: 'Mon cadeau est employé.', type: 'REFRAIN', number: 4 },
  ],
  105: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 12, text: 'Pour notre dernière chanson, on vous sort notre meilleur son', type: 'COUPLET', number: 1 },
    { time: 17, text: 'On vous partage des anecdotes, sans que Louis ne baisse son froc', type: 'COUPLET', number: 1 },
    { time: 24, text: 'En parlant de fiak, on voulait parler de Gaïa et de sa chatte', type: 'COUPLET', number: 1 },
    { time: 30, text: 'Caressé par un Mathis pas ouf, qui s\'est perdu dans sa touffe', type: 'COUPLET', number: 1 },
    { time: 36, text: 'Du haut de la CN Tower, pour certains c\'est leur rêve de coeur', type: 'COUPLET', number: 1 },
    { time: 42, text: 'La la la dans le fiak, la la la la dans sa chatte', type: 'COUPLET', number: 1 },
    { time: 50, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 1 },
    { time: 56, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 1 },
    { time: 62, text: 'Lucas toujours AFK, quand il est là on ne le sait pas', type: 'COUPLET', number: 2 },
    { time: 69, text: '11 purple, tu es notre roi, c\'est passé comme dans Gaïa', type: 'COUPLET', number: 2 },
    { time: 76, text: 'C\'est Louis qui a tout bu, avant de nous montrer son cul', type: 'COUPLET', number: 2 },
    { time: 82, text: 'Gaïa en a vomi, dans une casserole toute la nuit', type: 'COUPLET', number: 2 },
    { time: 88, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 2 },
    { time: 93, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 2 },
    { time: 99, text: 'En revenant sur Toronto, Chinatown, c\'est pas beau', type: 'COUPLET', number: 3 },
    { time: 104, text: 'Oh putain Laurent, avec les flics c\'est pas marrant', type: 'COUPLET', number: 3 },
    { time: 108, text: 'Chatime donne des frissons à cause des clés tout sur le paillasson', type: 'COUPLET', number: 3 },
    { time: 113, text: 'Shawarma ou pizza, que des dilemmes sans choix', type: 'COUPLET', number: 3 },
    { time: 119, text: 'Entre deux tatouages on a choisi, celui qu\'on préfère celui des nazis', type: 'COUPLET', number: 3 },
    { time: 126, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 3 },
    { time: 132, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 3 },
    { time: 139, text: 'Dans ce groupe chacun a des défauts, même si Louis a le plus gros', type: 'COUPLET', number: 4 },
    { time: 143, text: 'Gaïa est une grosse guauchiasse, qui soutire le Hamas', type: 'COUPLET', number: 4 },
    { time: 149, text: 'Tandis que Lucas est écolo, voulant son bilan carbone à zéro', type: 'COUPLET', number: 4 },
    { time: 155, text: 'Pour Louis les tips n\'existent pas, sauf pour le gars avec les pizzas', type: 'COUPLET', number: 4 },
    { time: 161, text: 'Il ne sait pas non plus faire les accents, Tabarnak, Calisse, Chris, Poutine vraiment', type: 'COUPLET', number: 4 },
    { time: 167, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 4 },
    { time: 173, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 4 },
    { time: 180, text: 'Pour notre dernière soirée au bistrot, un bras de fer n\'est pas de trop', type: 'COUPLET', number: 5 },
    { time: 184, text: 'Même si Enrique a abusé avec la mère de Louis tanée', type: 'COUPLET', number: 5 },
    { time: 187, text: 'Gaïa partant avec Samuel qui voulait l\'envoyer au septième ciel', type: 'COUPLET', number: 5 },
    { time: 190, text: 'Louis partant avec son gland, personne ne l\'a trouvé charmant', type: 'COUPLET', number: 5 },
    { time: 193, text: 'Ni Maylouane, ni Mariga n\'a pu être pour lui les chutes du Niagara', type: 'COUPLET', number: 5 },
    { time: 198, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 5 },
    { time: 204, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 5 },
    { time: 210, text: 'C\'est la fin de la mobi, on part presque tous d\'ici', type: 'REFRAIN', number: 6 },
    { time: 216, text: 'Au revoir Chicoutimi, on reviendra c\'est promis', type: 'REFRAIN', number: 6 },
  ],
  
  106: [
    { time: 0, text: '...', type: 'INSTRUMENTAL', number: 1 },
    { time: 6, text: 'Vive Chicout\', vive Chicout\' !', type: 'REFRAIN', number: 1 },
    { time: 9, text: 'Vive Chicout\' l\'hiver !', type: 'REFRAIN', number: 1 },
    { time: 13, text: 'Qui s\'en prend derrière, devant !', type: 'REFRAIN', number: 1 },
    { time: 16, text: 'Louis en garde un goût amer !', type: 'REFRAIN', number: 1 },
    { time: 19, text: 'OOOH ! Vive Chicout\', vive Chicout\' !', type: 'REFRAIN', number: 1 },
    { time: 22, text: 'Vive Chicout\' l\'hiver !', type: 'REFRAIN', number: 1 },
    { time: 26, text: 'Boules de sperme et jour de gland !', type: 'REFRAIN', number: 1 },
    { time: 29, text: 'Et paf dans le cul d\'ta mère !', type: 'REFRAIN', number: 1 },
    { time: 32, text: 'Sur le long chemin,' , type: 'COUPLET', number: 1 },
    { time: 35, text: 'Quand Gaïa se déhanche,' , type: 'COUPLET', number: 1 },
    { time: 39, text: 'Un vieux monsieur s\'avance,' , type: 'COUPLET', number: 1 },
    { time: 42, text: 'Lucas ne dira rien,' , type: 'COUPLET', number: 1 },
    { time: 45, text: 'Louis n\'est pas content,' , type: 'COUPLET', number: 1 },
    { time: 48, text: 'La guerre se déclenche' , type: 'COUPLET', number: 1 },
    { time: 52, text: 'Il lui attrape la panse,' , type: 'COUPLET', number: 1 },
    { time: 55, text: 'Jusqu\'à ne plus avoir de sang !' , type: 'COUPLET', number: 1 },
    { time: 58, text: 'OOOH ! Vive Chicout\', vive Chicout\' !' , type: 'REFRAIN', number: 2 },
    { time: 62, text: 'Vive Chicout\' l\'hiver !' , type: 'REFRAIN', number: 2 },
    { time: 65, text: 'Qui s\'en prend derrière, devant !' , type: 'REFRAIN', number: 2 },
    { time: 68, text: 'Louis en garde un goût amer !' , type: 'REFRAIN', number: 2 },
    { time: 72, text: 'OOOH ! Vive Chicout\', vive Chicout\' !' , type: 'REFRAIN', number: 2 },
    { time: 75, text: 'Vive Chicout\' l\'hiver !' , type: 'REFRAIN', number: 2 },
    { time: 78, text: 'Boules de sperme et jour de gland !' , type: 'REFRAIN', number: 2 },
    { time: 81, text: 'Et paf dans le cul d\'ta mère !' , type: 'REFRAIN', number: 2 },
    { time: 88, text: 'Mais le vieux monsieur,' , type: 'COUPLET', number: 2 },
    { time: 91, text: 'Venant de ce village,' , type: 'COUPLET', number: 2 },
    { time: 94, text: 'Yves n\'est pas très sage,' , type: 'COUPLET', number: 2 },
    { time: 97, text: 'Dans son slip c\'est le feu' , type: 'COUPLET', number: 2 },
    { time: 100, text: 'À en perdre la raison,' , type: 'COUPLET', number: 2 },
    { time: 104, text: 'jusqu\'à la grosse giclette,' , type: 'COUPLET', number: 2 },
    { time: 107, text: 'Partout s\'en jette,' , type: 'COUPLET', number: 2 },
    { time: 110, text: 'Bien plus que ses estimations !' , type: 'COUPLET', number: 2 },
    { time: 113, text: 'OOOH ! Vive Chicout\', vive Chicout\' !' , type: 'REFRAIN', number: 3 },
    { time: 118, text: 'Vive Chicout\' l\'hiver !' , type: 'REFRAIN', number: 3 },
    { time: 120, text: 'Qui s\'en prend derrière, devant !' , type: 'REFRAIN', number: 3 },
    { time: 123, text: 'Louis en garde un goût amer !' , type: 'REFRAIN', number: 3 },
    { time: 127, text: 'OOOH ! Vive Chicout\', vive Chicout\' !' , type: 'REFRAIN', number: 4 },
    { time: 130, text: 'Vive Chicout\' l\'hiver !' , type: 'REFRAIN', number: 4 },
    { time: 133, text: 'Boules de sperme et jour de gland !' , type: 'REFRAIN', number: 4 },
    { time: 136, text: 'Et paf dans le cul d\'ta mère !' , type: 'REFRAIN', number: 4 },
    { time: 140, text: 'Joyeux, joyeux Noël !', type: 'BRIDGE', number: 1 },
    { time: 143, text: 'Aux mille gâteries...', type: 'BRIDGE', number: 1 },
    { time: 146, text: 'Mathis le démentiel,' , type: 'BRIDGE', number: 1 },
    { time: 150, text: 'Gaïa ne nous a pas choisi' , type: 'BRIDGE', number: 1 },
    { time: 152, text: 'OOOH ! Vive Chicout\', vive Chicout\' !' , type: 'REFRAIN', number: 5 },
    { time: 156, text: 'Vive Chicout\' l\'hiver !' , type: 'REFRAIN', number: 5 },
    { time: 160, text: 'Qui s\'en prend derrière, devant !', type: 'REFRAIN', number: 5 },
    { time: 162, text: 'Louis en garde un goût amer !', type: 'REFRAIN', number: 5 },
    { time: 166, text: 'OOOH ! Vive Chicout\', vive Chicout\' !', type: 'REFRAIN', number: 5 },
    { time: 169, text: 'Vive Chicout\' l\'hiver !', type: 'REFRAIN', number: 5 },
    { time: 173, text: 'Boules de sperme et jour de gland !', type: 'REFRAIN', number: 5 },
    { time: 176, text: 'Et paf dans le cul d\'ta mère !', type: 'REFRAIN', number: 5 },
  ],
}

export function useLyrics(trackId: Ref<number>) {
  const lyrics = ref<LyricLine[]>([])
  const currentTime = ref(0)
  const isLoading = ref(false)

  // Fetch lyrics for a track
  const fetchLyrics = async (): Promise<void> => {
    isLoading.value = true

    // TODO: Replace with API call when backend is ready
    // const { get } = useApi()
    // const response = await get<LyricsData>(`/tracks/${trackId.value}/lyrics`)
    // if (response.success) {
    //   lyrics.value = response.data.lines
    // }

    // For now, use local data
    lyrics.value = localLyricsData[trackId.value] || []
    isLoading.value = false
  }

  // Current lyric index based on time
  const currentLyricIndex = computed(() => {
    const time = currentTime.value
    for (let i = lyrics.value.length - 1; i >= 0; i--) {
      const lyric = lyrics.value[i]
      if (lyric && time >= lyric.time) {
        return i
      }
    }
    return 0
  })

  // Previous, current, and next lyrics
  const previousLyric = computed(() => {
    const idx = currentLyricIndex.value
    return idx > 0 ? lyrics.value[idx - 1]?.text ?? '' : ''
  })

  const currentLyric = computed(() => {
    return lyrics.value[currentLyricIndex.value]?.text ?? ''
  })

  const nextLyric = computed(() => {
    const idx = currentLyricIndex.value
    return idx < lyrics.value.length - 1 ? lyrics.value[idx + 1]?.text ?? '' : ''
  })

  // Current section type and number (for visualizer effects)
  const currentSectionType = computed(() => {
    return lyrics.value[currentLyricIndex.value]?.type ?? 'INSTRUMENTAL'
  })

  const currentSectionNumber = computed(() => {
    return lyrics.value[currentLyricIndex.value]?.number ?? 1
  })

  // Check if track has lyrics
  const hasLyrics = computed(() => {
    return trackId.value in localLyricsData
  })

  // Update current time (called from audio player)
  const updateTime = (time: number) => {
    currentTime.value = time
  }

  // Watch for track changes - reset time and reload lyrics
  watch(trackId, () => {
    currentTime.value = 0  // Reset time when track changes
    fetchLyrics()
  }, { immediate: true })

  return {
    // State
    lyrics: readonly(lyrics),
    isLoading: readonly(isLoading),
    currentLyricIndex,
    previousLyric,
    currentLyric,
    nextLyric,
    currentSectionType,
    currentSectionNumber,
    hasLyrics,

    // Methods
    fetchLyrics,
    updateTime,
  }
}
